plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
branches:
  - name: main
  - name: beta
    prerelease: true
    channel: beta
  - name: alpha
    prerelease: true
    channel: alpha
  - name: +([0-9])?(.{+([0-9]),x}).x